# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default=None, upload_to='.'),
            preserve_default=False,
        ),
    ]
