# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import labeler.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeler', '0002_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_date',
            field=models.DateTimeField(default=None, verbose_name='Date photo was uploaded.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=labeler.models.user_images_directory),
        ),
    ]
