# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import labeler.models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0004_auto_20170803_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='image',
            name='taken_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(default=None, max_length=512, null=True, verbose_name='Description of the image, where and when it was taken'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=labeler.models.user_images_directory, verbose_name='Select file to upload'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
