# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0005_auto_20170804_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalvotes',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='labeler.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='images', verbose_name='Select file to upload'),
        ),
    ]
