# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0007_auto_20170821_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='images', verbose_name='Image to be labeled'),
        ),
    ]
