# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0008_auto_20170823_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='info',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Metadata about the image (usually from the EXIF header)'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date photo was created.'),
        ),
    ]
