# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0010_auto_20170829_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(choices=[('Wolf', 'Wolf'), ('Fox', 'Fox'), ('Wolverine', 'Wolverine'), ('Rabbit', 'Rabbit')], default=None, max_length=256, null=True),
        ),
    ]
